// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_history.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatHistory = `-- name: CreateChatHistory :one
INSERT INTO chat_history (
  user_id,
  query,
  ai_response,
  retrieved_context
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, query, ai_response, retrieved_context, created_at
`

type CreateChatHistoryParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	Query            string      `json:"query"`
	AiResponse       string      `json:"ai_response"`
	RetrievedContext []byte      `json:"retrieved_context"`
}

func (q *Queries) CreateChatHistory(ctx context.Context, arg CreateChatHistoryParams) (ChatHistory, error) {
	row := q.db.QueryRow(ctx, createChatHistory,
		arg.UserID,
		arg.Query,
		arg.AiResponse,
		arg.RetrievedContext,
	)
	var i ChatHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Query,
		&i.AiResponse,
		&i.RetrievedContext,
		&i.CreatedAt,
	)
	return i, err
}

const getChatHistoryByUserID = `-- name: GetChatHistoryByUserID :many
SELECT id, user_id, query, ai_response, retrieved_context, created_at
FROM chat_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetChatHistoryByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetChatHistoryByUserID(ctx context.Context, arg GetChatHistoryByUserIDParams) ([]ChatHistory, error) {
	rows, err := q.db.Query(ctx, getChatHistoryByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatHistory
	for rows.Next() {
		var i ChatHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Query,
			&i.AiResponse,
			&i.RetrievedContext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
